config/routes.rb
Rails.application.routes.draw do
  
  root   'static_page#home'

  resources :books
 
  match 'login',                 to: 'users#login',             as: 'login',             via: [:get, :post]
  match 'logout',                to: 'users#logout',            as: 'logout',            via: [:get, :post]
  match 'signup',                to: 'users#signup',            as: 'signup',            via: [:get, :post]
  match 'account',               to: 'users#account',           as: 'account',           via: [:get, :post]
  match 'account/destroy',       to: 'users#destroy',           as: 'destroy',           via: [:get, :post]

  match 'lost_password',         to: 'users#lost_password',     as: 'lost_password',     via: [:get, :post]
  match 'password_recovery/:id', to: 'users#password_recovery', as: 'password_recovery', via: [:get, :post, :patch]

  scope module: 'admin' do
    resources :users
    resources :genres
    resources :authors
  end

  get '*unmatched_route', to: 'application#render_404'

end

app/models/author.rb
class Author < ApplicationRecord
    
    has_many :books, dependent: :destroy

    validates :first_name, :last_name, presence: true

    def name 
        "#{first_name} #{last_name}"
    end
    
end

app/controllers/admin/authors_controller.rb
class Admin::AuthorsController < ApplicationController
    
    before_action :require_admin
    before_action :find_author, only: [:show, :edit, :update, :destroy]

    def index
        @authors = Author.all
    end

    def new 
        @author = Author.new
    end

    def create
        @author = Author.new(author_params)
    
        if @author.save
          redirect_to authors_path
        else 
          render 'new'
        end
    end

    def edit 
    end

    def update
        unless @author.update_attributes(author_params)
            redirect_to edit_author_path, :flash => { :error => "Author was not updated! Not all required fields were filled." }
        else
            redirect_to authors_path, :flash => { :success => "Author successfully updated!" }
        end
    end

    def destroy
        @author.destroy
        redirect_to authors_path
    end

    private

        def author_params
            params.require(:author).permit(:first_name, :last_name) 
        end

        def find_author
            @author = Author.find(params[:id])
        end
end

app/views/admin/authors/_form.haml
= simple_form_for @author, defaults: { wrapper_html: { class: 'author-form' } }  do |f|
    = f.input :first_name, placeholder: "First name", label: false, autofocus: true
    = f.input :last_name, placeholder: "Last name", label: false
    = f.button :submit

app/views/admin/authors/edit.haml
%h1 Edit author information

= render 'form'

%hr

%h2 Edit author books 

- @author.books.each do |book|
    .books-block
        .book-info
            .book-img
                %a{:href => "/books/<%= book.id %>"}
                =image_tag book.book_img.url(:book_index)
        .book-description
            %p=     "Author: #{book.author.name}"
            %p= "Title: #{book.title}"
            %p= "Genres: #{book.genres.map {|genre| genre.name}.join(", ")}"
            %p= truncate("Description: #{book.description}", :length => 30)
        
        .bottom-book-menu
            %p= link_to "More", book
            - if User.current.admin?
                %p= link_to "Edit", edit_book_path(book)
                %p= link_to "Delete", book_path(book), data: { confirm: "Are you sure?" }, :method => :delete

app/views/admin/authors/index.haml
%h1 Listing authors

%table
    %thead
        %tr
        %th First name
        %th Last name
        %th Books
        %th
        %th

    %tbody
    - @authors.each do |author|
        %tr
            %td= author.first_name
            %td= author.last_name
            %td= "#{author.books.map {|book| book.title}.join(", ")}"
            %td= link_to "Edit", edit_author_path(author)
            %td= link_to "Delete", author_path(author), data: { confirm: "Are you sure?" }, :method => :delete

%br

= link_to 'New author', new_author_path

app/views/admin/authors/new.haml
%h1 Create author

= render 'form'