config/routes.rb
Rails.application.routes.draw do
  
  root   'static_page#home'

  resources :books
 
  match 'login',                 to: 'users#login',             as: 'login',             via: [:get, :post]
  match 'logout',                to: 'users#logout',            as: 'logout',            via: [:get, :post]
  match 'signup',                to: 'users#signup',            as: 'signup',            via: [:get, :post]
  match 'account',               to: 'users#account',           as: 'account',           via: [:get, :post]
  match 'account/destroy',       to: 'users#destroy',           as: 'destroy',           via: [:get, :post]

  match 'lost_password',         to: 'users#lost_password',     as: 'lost_password',     via: [:get, :post]
  match 'password_recovery/:id', to: 'users#password_recovery', as: 'password_recovery', via: [:get, :post, :patch]

  scope module: 'admin' do
    resources :users
    resources :genres
    resources :authors
  end

  get '*unmatched_route', to: 'application#render_404'

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title
      =content_for(:page_title) || BookStore
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', 'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.bundle.min.js'
  %body
    .nav-bar
      - if User.current.logged?
        %li.logout 
          %a
            = form_tag logout_path do
              = submit_tag 'Log Out', :class=>'logout-btn'
        %li= link_to "Books", books_path
        %li.profile= link_to "#{User.current.name}", account_path
        - if User.current.admin?
          %li= link_to "Authors", authors_path 
          %li= link_to "Genres", genres_path 
          %li= link_to "Users", users_path 
      - else 
        %li= link_to "Sign Up", signup_path
        %li= link_to "Log In", login_path
        %li= link_to "Home", root_path

    - flash.each do |key, value|
      .alert{ :class => "alert-#{key}" }
        %button.close{ :data => { :dismiss => "alert" } } x
        %strong.alert_message
          = value

    .container
      = yield